### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dylanseago** [LedgerHQ/ledgerjs#147]
The following code:
```javascript
import Transport from '@ledgerhq/hw-transport-u2f'
import AppEth from '@ledgerhq/hw-app-eth'
Transport.create().then((transport) => new AppEth(transport).getAppConfiguration())
  .then(console.log).catch(console.error)
```
Produces this error:
```
TypeError: Cannot read property 'length' of undefined
    at wrapApdu (TransportU2F.js?95a8:61)
    at attemptExchange (TransportU2F.js?95a8:77)
    at TransportU2F._callee2$ (TransportU2F.js?95a8:183)
    at tryCatch (runtime.js?4a57:62)
    at Generator.invoke [as _invoke] (runtime.js?4a57:296)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at step (asyncToGenerator.js?7b11:17)
    at eval (asyncToGenerator.js?7b11:35)
    at new Promise (<anonymous>)
    at new F (_export.js?90cd:35)
```

Environment:
```
> node --version
v8.9.4
> npm ls | grep ledgerhq
├─┬ @ledgerhq/hw-app-eth@4.7.3
│ └── @ledgerhq/hw-transport@4.7.3 deduped
├─┬ @ledgerhq/hw-transport-u2f@4.7.3
│ ├── @ledgerhq/hw-transport@4.7.3 deduped
```
Browser:
```
Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
Revision | dc3469be277cc962ba01d9c0cb5bb1a265676c36-refs/branch-heads/3325@{#725}
OS | Mac OS X
JavaScript | V8 6.5.254.41
```

**Comment by passabilities** [comment]
:+1: I'm getting the same error

**Comment by gre** [comment]
was able to reproduce on https://codesandbox.io/s/znzky28yy3

fix should be this: https://github.com/LedgerHQ/ledgerjs/pull/163

**Comment by gre** [comment]
Fixed: https://codesandbox.io/s/l9nmp942r7

<img width="414" alt="capture d ecran 2018-06-07 a 20 42 24" src="https://user-images.githubusercontent.com/211411/41119565-654f5b44-6a93-11e8-9746-0c72a6bd3c5f.png">

**Comment by satb** [comment]
I still get the same error using v5.3.0 of the transport library and Chrome  79.0.3945.88
```
TypeError: Cannot read property 'length' of undefined
    at wrapApdu (TransportU2F.js:41)
    at attemptExchange (TransportU2F.js:57)
    at TransportU2F._callee2$ (TransportU2F.js:179)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at step (TransportU2F.js:23)
    at TransportU2F.js:23
    at new Promise (<anonymous>)
    at TransportU2F.<anonymous> (TransportU2F.js:23)
```

**Comment by cacampbell** [comment]
This is definitely still an issue, which is concerning if this is meant to be the standard transport for apps on windows.

**Comment by cacampbell** [comment]
For me, it was scrambleKey, which is not mentioned in the docs because they are just copy-pasted from the webusb transport. U2F needs:

```
transport.setScrambleKey(<string>);
```

and for the string provided to match the U2F_PROXY_MAGIC define in the Makefile of the BOLOS app. 

Hope this helps someone.
