### ISSUE TITLE
Can't confirm with MEW using Windows 10 1903

### ISSUE THREAD

**Issue by ljq8896** [LedgerHQ/ledgerjs#370]
Hi, @gre 
OS Windows 10 1903
Browser Chrome 75
Device & Firmware Ledger Nano S 1.5.5
App Ethereum 1.2.7
I have followed the troubleshooting [here](https://support.ledger.com/hc/en-us/articles/360023190873-Windows-10-Update-Changes-for-Ledger-Users).
When I confirm a transcation by interact with device, the popup window shows "Couldn't complete sign-in. Try again and be sure to do the follow-up action" and Ledger nano s takes no respond and freeze. Before   click ✓ I can click ✗ to cancel it normally.
How would it happened? I think Windows Hello API is using Webauthn not u2f. U2F is no longer supported in Windows 10 1903. As Using Chrome 71 and below with MEW, there won't show select account page. But now neither MEW nor MyCrypto support Webauthn.
The Webusb method has some problem with Windows. But perform well in Android. I think using Mycrypto with Chrome for Android is a better way to access erc20 tokens easily now.

**Comment by gre** [comment]
this was a known bug caused by a Windows update and is fixed since then

**Comment by Hey** [comment]
Hi @gre ,

I still experience this issue with Ethereum using Metamask and Brave, I tried both Brave's built in metamask and the metamask extension.
Sometimes it works, I tried both my Nano S and my Nano X. And on two different computers. I tried switching cables too. I reinstalled apps as well.

**Comment by DanielBeckDK** [comment]
No matter what I did, I could not fix this issue on windows. So I followed [this tutorial](https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview) to create a bootable Ubuntu USB.

I booted a laptop from the ubuntu USB and I had no troubles using my ledger nano S in ubuntu. I spent days trying to get to some coins I had on there. It cost me a pretty penny not to be able to get to my coins when I needed to so I'll never use any Ledger device again, but this is a way to get to your coins.
